# Generated by Django 3.0.8 on 2021-05-16 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20210512_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='price',
        ),
        migrations.RemoveField(
            model_name='check',
            name='product',
        ),
        migrations.RemoveField(
            model_name='check',
            name='quantity',
        ),
        migrations.AddField(
            model_name='check',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductInCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(200.0), django.core.validators.MinValueValidator(0.01)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='products',
            field=models.ManyToManyField(to='shop.ProductInCheck'),
        ),
    ]
